[metadata]
  name = "bitswapN"
  author = "Adin Schmahmann"

[global]
  plan = "data-transfer"
  case = "bitswapN"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "group1"
  [groups.instances]
    count = 2
  [groups.run]
    [groups.run.test_params]
      latency = "10ms"
      bandwidth = "10MiB"
      transports = "tcp"
      muxers = "yamux"
      security = "tls"
      servertype = "simplified"
      dagtype="deep-ipld"
      dagparams="{\"Padding\" : \"128 KiB\", \"Depth\" : 200}"
      bslatency = "0ms"
      manifestfetchtype = "none"
      manifetchbslatency = "0ms"